### ISSUE TITLE
Can't connect/start frozen server with ip forwarding services

### ISSUE THREAD

**Issue by Bush-cat** [gekware/minecraft-server-hibernation#131] opened 2022-02-07 11:22 UTC
I tried ngrok and playit.gg to to expose the port 25555 in tcp for other players to join but they can't connect/ start the server when the server is frozen but they can connect to the server when I start the server from the local network.

**Comment by Bush-cat** [comment] 2022-02-07 13:07
Log of the connection (Playit.gg)
https://nekobin.com/welovomupe

**Comment by Bush-cat** [comment] 2022-02-07 13:15
I've used it years ago before on papermc 1.16.5 with msh 2.3.5, I restored that backup and retried and it worked there but it's not working with the fabricmc 1.18.1 msh 2.4.4, I will try the old msh version next and look to get some logs from msh.

**Comment by gekigek99** [comment] 2022-02-07 15:58
> they can't connect/ start the server when the server is frozen but they can connect to the server when I start the server from the local network.

- so if msh is at `mshaddress.com:25555` they can join a running server but cannot start it?
- are you sure your friends are using port 25555 and not 25565? and the port 25555 is open on server/those services?
- where are you hosting msh and minecraft server?

> it's not working with the fabricmc 1.18.1 msh 2.4.4

what logs does msh show?

> look to get some logs from msh.

set `Debug` to 3

**Comment by Bush-cat** [comment] 2022-02-07 22:24
the server runs on a local laptop running x64 Ubuntu Server 20.04 LTS, I access it from ssh and detach msh with screen.
when the server was started it works but when the server is frozen minecraft times out when connecting

msh log:
```
2022/02/07 21:43:30 [info  *   ] checking OS support...
2022/02/07 21:43:30 [info  *   ] loading config default...
2022/02/07 21:43:30 [info  *   ] loading config runtime...
2022/02/07 21:43:30 [info  ****] log level set to: 3
2022/02/07 21:43:30 [info  *   ] msh proxy setup: 0.0.0.0:25555 --> 127.0.0.1:25565
2022/02/07 21:43:30 [info  *   ] checking version...
2022/02/07 21:43:30 [info  ****] msh (v2.4.4) is running an unofficial release
2022/02/07 21:43:30 [info  *   ] listening for new clients to connect on 0.0.0.0:25555...
2022/02/07 21:43:36 [error *   ] HandleClientSocket: getReqType: client request unknown
2022/02/07 21:43:38 [error *   ] HandleClientSocket: getReqType: client request unknown
```

playit.gg log is spammed with:
```
Feb 07 13:00:21.105 INFO CONNECTION COUNTS: 16 tcp, 0 udp, version: 0.4.6
Feb 07 13:00:22.383 INFO 88.152.185.253:48746/tcp tunnel=>host: closed due to agent close, mapping: tunnel=>host, client_addr: 88.152.185.253:48746, version: 0.4.6
Feb 07 13:00:22.437 INFO 88.152.185.253:2836/tcp: new client connecting to 192.168.188.71:25555, version: 0.4.6
Feb 07 13:00:22.475 INFO CONNECTION COUNTS: 17 tcp, 0 udp, version: 0.4.6
Feb 07 13:00:41.373 INFO Allocator: used packets: 17, free packets: 46, version: 0.4.6
Feb 07 13:00:52.405 INFO 88.152.185.253:2836/tcp tunnel=>host: closed due to agent close, mapping: tunnel=>host, client_addr: 88.152.185.253:2836, version: 0.4.6
Feb 07 13:01:41.375 INFO Allocator: used packets: 17, free packets: 46, version: 0.4.6
Feb 07 13:02:41.376 INFO Allocator: used packets: 17, free packets: 46, version: 0.4.6
```

I tried the old msh 2.3.5 version and it had the same issue but minecraft says "disconnected" instead of timeout and it shows the server as hibernating while the new version keeps saying pinging without ever giving a result.
msh 2.3.5 log:
```
2022/02/07 21:56:55 *** listening for new clients to connect on 0.0.0.0:25555 ...
2022/02/07 21:57:01 closing connection for: 192.168.188.71
2022/02/07 21:57:06 *** player unknown requested server info from 192.168.188.71:25555 to 127.0.0.1:25565
2022/02/07 21:57:06 closing connection for: 192.168.188.71
2022/02/07 21:57:07 closing connection for: 192.168.188.71
```

the connection msh closes is false, 192.168.188.71 is the ip of the minecraft server, aka 0.0.0.0.
this is how it should behave like when I directly connect to the ip from my pc 192.168.188.99:
```
2022/02/07 22:04:04 [info  *   ] player unknown requested server info from 192.168.188.99:25555 to 127.0.0.1:25565
2022/02/07 22:04:04 [info  *   ] closing connection for: 192.168.188.99
2022/02/07 22:03:56 [info  *** ] MINECRAFT SERVER IS STARTING!
2022/02/07 22:03:56 [info  *   ] Bushccat tried to join from 192.168.188.99:25555 to 127.0.0.1:25565
2022/02/07 22:03:56 [info  *   ] closing connection for: 192.168.188.99
```

after starting the server from a direct connection and then connecting to the running server over the playit.gg again outputs this:
```
2022/02/07 22:07:59 [info  *   ] forward: closing       127.0.0.1 -->  192.168.188.99 because of: EOF
2022/02/07 22:07:59 [info  *   ] forward: closing  192.168.188.99 -->       127.0.0.1 because of: EOF
2022/02/07 22:07:59 [info  *   ] forward: closing       127.0.0.1 -->  192.168.188.71 because of: EOF
2022/02/07 22:07:59 [info  *   ] forward: closing  192.168.188.71 -->       127.0.0.1 because of: EOF
2022/02/07 22:08:04 [serv  **  ] [22:08:04] [User Authenticator #2/INFO]: UUID of player Bushccat is 03282ca3-24d8-4ab3-b2d2-e667f3ddd181
2022/02/07 22:08:04 [serv  **  ] A PLAYER JOINED THE SERVER! - 1 players online
2022/02/07 22:08:04 [serv  **  ] [22:08:04] [Server thread/INFO]: Bushccat[/127.0.0.1:54580] logged in with entity id 1144 at (-2699.306395995536, 66.0, 2457.035258068494)
2022/02/07 22:08:04 [serv  **  ] [22:08:04] [Server thread/WARN]: Player Bushccat can't receive direct packet, using nbt packet instead
2022/02/07 22:08:04 [serv  **  ] [22:08:04] [Server thread/INFO]: Bushccat joined the game
```

I checked the minecraft client logs too
when hibernated:
`[23:15:15] [Render thread/ERROR]: Can't ping yellow-underwear.auto.playit.gg: Timed out`

when started:
```
[23:17:20] [Render thread/INFO]: Connecting to yellow-underwear.auto.playit.gg, 25565
[23:17:21] [Render thread/INFO]: Started 10 worker threads
```

it is weird for me that it says 25565 since I setup 25555 in playit as seen in the playit log

I hope that some of this information was useful and that this problem can be sorted out.
Thank you for this amazing piece of software and your hard work.

**Comment by gekigek99** [comment] 2022-02-08 23:39
Ok thanks for all the info, I think I have an explanation for what is happening... ;)

The problem is that msh knows what the client is trying to do _(join or request server info)_ by recognizing 3 bytes sent in the first connection packet. 2 that represent the port of server and 1 that is the join or info signal.

https://github.com/gekware/minecraft-server-hibernation/blob/afddade4a14b0654a7e404f5d2c2ee13a85f89f8/lib/conn/conn-prot.go#L108-L122

Now, if the client is on the same network (not using a proxy like playit.gg) the client first packet will contain `port(25555), 2` and this is recognized by msh which starts the server.
If the client is using a proxy, the client first packet will contain `port(48746), 2` and this is NOT expected by msh which won't start the server, returning:

```
2022/02/07 21:43:36 [error *   ] HandleClientSocket: getReqType: client request unknown
2022/02/07 21:43:38 [error *   ] HandleClientSocket: getReqType: client request unknown
```
_this also explains why on version 2.3.5 the info request works but not the join (if you are interested I can explain it to you but for sake of efficiency i'll stick to the lastest version)_

---

### solution 1

the first/fast solution is: can you set the playit.gg port to `25555`? instead of `48746` or `2836` or whatever they are, i took those number from here:

```
Feb 07 13:00:22.383 INFO 88.152.185.253:48746/tcp tunnel=>host: closed due to agent close, mapping: tunnel=>host, client_addr: 88.152.185.253:48746, version: 0.4.6
Feb 07 13:00:22.437 INFO 88.152.185.253:2836/tcp: new client connecting to 192.168.188.71:25555, version: 0.4.6
```

### solution 2

If not I'll make a branch to implement a bugfix for this (just need to add 2 other cases to the switch statement I showed you before: the first returning `CLIENT_REQ_INFO` if the last byte is `0` or `1` the second returning `CLIENT_REQ_JOIN` if the last byte is `2`.

_If you want you can give it a try implementing that and then do a pr so you became an official contributor, just tell me before doing so. In any case I think I'll still need you to test it since yours is a peculiar case_

---

> Thank you for this amazing piece of software and your hard work.

Thanks so much, I **really** appreciate this comment :)

**Comment by Bush-cat** [comment] 2022-02-09 20:51
Thank you so much for helping me out

Solution 1 can't be applied because the forwarding services selects a random unused port for the client which can't be set with ngrok nor playit.gg maybe the premium plans allow a custom port there but decided to host my own server because I don't have much money because I need to finish school. 

Solution 2 I tried for hours to get my new code working but I'm a such beginner in C (and never used golang) and couldn't do it but I'll give my best testing your fixes when you are ready.

**Comment by gekigek99** [comment] 2022-02-09 21:09
> Solution 2 I tried for hours to get my new code working but I'm a such beginner in C (and never used golang) and couldn't do it but I'll give my best testing your fixes when you are ready.

ok no problem! I'll think a bit about a solution (apparently its a bit more complicated than what I described before). In the meanwhile feel free to take a look at the rep code, maybe you can learn something new!

> the forwarding services selects a random unused port for the client which can't be set with ngrok nor playit.gg

But after you have been assigned a port it does not change in time anymore right? all of your clients/friends use the same port to connect no? _if yes maybe there is still hope for an easy fix_

**Comment by Bush-cat** [comment] 2022-02-10 22:10
> But after you have been assigned a port it does not change in time anymore right? all of your clients/friends use the same port to connect no? Cause in that case the fix would just be to set `msh ListenPort` to the port `48746` (as example, instead of 25555) so that the connection looks like this: `client -> playit.gg on 48746 -> msh on 48746 -> minecraft server on 25565`

the port services like playit.gg give a random available port when someone connects, when he disconnects and reconnects you get a new random port. One time when I was using ngrok and had my old ngrok ip address I was able to connect to someone elses server that was running on my old port and one time someone joined my server from ngrok and left a sign in the world and I found him in the log, then I enabled the whitelist.

**Comment by gekigek99** [comment] 2022-02-10 22:53
ok that's unfortunate

I'll need to implement a full fix for this then...

_Would you mind joining the discord server [here](https://github.com/gekware/minecraft-server-hibernation/discussions/75)? I wanted to ask you a question related to these forwarding services_

**Comment by gekigek99** [comment] 2022-02-11 01:29
should be fixed in 8f8c3dee555073828b529fe802fa2f8fc754b927

can you compile the branch [bugfix/request-type-analyzer](https://github.com/gekware/minecraft-server-hibernation/tree/bugfix/request-type-analyzer) and test it?

**Comment by Bush-cat** [comment] 2022-02-11 19:28
> should be fixed in [8f8c3de](https://github.com/gekware/minecraft-server-hibernation/commit/8f8c3dee555073828b529fe802fa2f8fc754b927)
> 
> can you compile the branch [bugfix/request-type-analyzer](https://github.com/gekware/minecraft-server-hibernation/tree/bugfix/request-type-analyzer) and test it?

great job, it's working well and shows the server info when hibernated too.
Again big thank you for doing this.

some small details 
when starting the server minecraft times out for both playit and direct connection and doesn't get the percentage but i's not a big issue but I grabbed the log if needed:
```
2022/02/11 19:02:20 [info  ****] log level set to: 3
2022/02/11 19:02:20 [info  *   ] msh proxy setup: 0.0.0.0:25555 --> 127.0.0.1:25565
2022/02/11 19:02:20 [info  *   ] checking version...
2022/02/11 19:02:20 [info  ****] msh (v2.4.5) is running an unofficial release
2022/02/11 19:02:20 [info  *   ] listening for new clients to connect on 0.0.0.0:25555...
2022/02/11 19:02:27 [info  *   ] player unknown requested server info from 127.0.0.1:25555 to 127.0.0.1:25565
2022/02/11 19:02:27 [info  *   ] closing connection for: 127.0.0.1
2022/02/11 19:02:57 [error *   ] extractPlayerName: getClientPacket: error during clientSocket.Read()
2022/02/11 19:02:57 [info  *   ] whitelist not enabled
2022/02/11 19:02:57 [info  *** ] MINECRAFT SERVER IS STARTING!
2022/02/11 19:02:57 [info  *   ] player unknown tried to join from 192.168.188.71:25555 to 127.0.0.1:25565
2022/02/11 19:02:57 [info  *   ] closing connection for: 192.168.188.71
2022/02/11 19:03:00 [serv  **  ] Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
// minecraft server starting logs
2022/02/11 19:04:13 [serv  **  ] [19:04:13] [Server thread/INFO]: Done (37.636s)! For help, type "help"
2022/02/11 19:04:13 [info  *** ] MINECRAFT SERVER IS ONLINE!
2022/02/11 19:04:15 [serv  **  ] [19:04:15] [Dynmap Render Thread/INFO]: [Dynmap] Loading resource pack standard
2022/02/11 19:04:15 [serv  **  ] a chat message was sent
2022/02/11 19:04:20 [info  *   ] forward: closing       127.0.0.1 -->  192.168.188.71 because of: EOF
2022/02/11 19:04:20 [info  *   ] forward: closing  192.168.188.71 -->       127.0.0.1 because of: EOF
2022/02/11 19:04:22 [serv  **  ] [19:04:22] [User Authenticator #1/INFO]: UUID of player Bushccat is 03282ca3-24d8-4ab3-b2d2-e667f3ddd181
2022/02/11 19:04:22 [serv  **  ] A PLAYER JOINED THE SERVER! - 1 players online
2022/02/11 19:04:23 [serv  **  ] [19:04:23] [Server thread/INFO]: Bushccat[/127.0.0.1:56488] logged in with entity id 695 at (-2710.2482657600003, 65.0, 2457.5884884500692)
2022/02/11 19:04:23 [serv  **  ] [19:04:23] [Server thread/WARN]: Player Bushccat can't receive direct packet, using nbt packet instead
2022/02/11 19:04:23 [serv  **  ] [19:04:23] [Server thread/INFO]: Bushccat joined the game
2022/02/11 19:04:29 [info  *   ] forward: closing       127.0.0.1 -->  192.168.188.99 because of: EOF
2022/02/11 19:04:29 [info  *   ] forward: closing  192.168.188.99 -->       127.0.0.1 because of: EOF
2022/02/11 19:04:29 [serv  **  ] [19:04:29] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 6950ms or 139 ticks behind
2022/02/11 19:09:09 [serv  **  ] [19:09:09] [Server thread/WARN]: Bushccat moved wrongly!
2022/02/11 19:09:16 [info  *   ] forward: closing  192.168.188.71 -->       127.0.0.1 because of: EOF
2022/02/11 19:09:16 [serv  **  ] [19:09:16] [Server thread/INFO]: Bushccat lost connection: Disconnected
2022/02/11 19:09:16 [serv  **  ] A PLAYER LEFT THE SERVER! - 0 players online
2022/02/11 19:09:16 [serv  **  ] [19:09:16] [Server thread/INFO]: Bushccat left the game
2022/02/11 19:09:19 [info  *   ] forward: closing  192.168.188.71 -->       127.0.0.1 because of: EOF
2022/02/11 19:09:20 [info  *   ] forward: closing       127.0.0.1 -->  192.168.188.71 because of: EOF
```

log for direct connection:
```
2022/02/11 19:23:42 [info  *   ] player unknown requested server info from 192.168.188.99:25555 to 127.0.0.1:25565
2022/02/11 19:23:42 [info  *   ] closing connection for: 192.168.188.99
2022/02/11 19:24:08 [error *   ] HandleClientSocket: getPing [1]: getClientPacket: error during clientSocket.Read()
2022/02/11 19:24:08 [info  *   ] closing connection for: 192.168.188.99
2022/02/11 19:24:21 [error *   ] extractPlayerName: getClientPacket: error during clientSocket.Read()
2022/02/11 19:24:21 [info  *   ] whitelist not enabled
2022/02/11 19:24:21 [info  *** ] MINECRAFT SERVER IS STARTING!
2022/02/11 19:24:21 [info  *   ] player unknown tried to join from 192.168.188.99:25555 to 127.0.0.1:25565
2022/02/11 19:24:21 [info  *   ] closing connection for: 192.168.188.99
2022/02/11 19:24:22 [serv  **  ] Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
```

**Comment by gekigek99** [comment] 2022-02-12 11:06
> the server icon is bugged, few pixels that look like symbols on a transparent background.

sometimes happen and it's a problem of the minecraft client, try launching again the client. If it's a recurrent problem open an other issue so we can discuss there. (if you do so please share also the png picture so I can test it and understand what is happening)

> when starting the server minecraft times out for both playit and direct connection and doesn't get the percentage

so you cannot see the message `Server start command issued. Please wait... 30%` when you are trying to join and the server is still warmin up? would you mind opening an issue for that describing again what you noticed _(full logs an your comment)_? (I would like to close this one)

> errors when nobody is online (don't know if this did something because the timeout stop is working)

don't know if it's related to the problems I just mentioned, if not, can you open an issue also for that?

It's better to open a new issue so we can start the discussion from a fresh start

**Closed** 2022-02-12 11:06 UTC

**Comment by PhotonRBLX** [comment] 2025-02-14 06:28
@Bush-cat could you show me how you configure the settings for playit.gg?? im trying everything to make it work with playit.gg but its not working, sorry its like 3 years already, but just incase you seen this comment and still remember how to do it.
