### ISSUE TITLE
(2.4.4) Error: getIpPorts: open server.properties: The system cannot find the file specified.

### ISSUE THREAD

**Issue by BolverBlitz** [gekware/minecraft-server-hibernation#136] opened 2022-03-12 23:07 UTC
To reproduce:
1 Download 2.4.4
2 Setup Config
3 Run it

If you try to run prerelease 2.4.4 you get that error:
`getIpPorts: open server.properties: The system cannot find the file specified.`

This error should not be trown, msh should start the MC server so it can generate the required config file and stop it again.

**Comment by gekigek99** [comment] 2022-04-02 19:12
the problem is that the user has to first accept the eula
maybe I can add warning/reminder to check the correct server path and launch the server for the first time?

**Comment by BolverBlitz** [comment] 2022-04-02 19:56
The user cant check it, because the file dosn´t exist until the server was started once.

**Comment by gekigek99** [comment] 2022-04-02 20:56
fixed in 3e28cca772f8a46d6e1a59fc52925250d9568220

@BolverBlitz do you confirm it's working?

**Closed** 2022-04-17 09:42 UTC
