### ISSUE TITLE
MSH crashed if being connected by a server botting tool

### ISSUE THREAD

**Issue by SeasonPhan** [gekware/minecraft-server-hibernation#156] opened 2022-07-31 02:24 UTC
### Current Behavior (🐛 Bug)

connection from any version from this [tool](https://github.com/games647/LambdaAttack/releases/tag/2.4.0) caused msh to crash
(minecraft server software doesnt seem to be affected by this)

### Expected Behavior

msh keep running+accepting connection like normal

### Steps to Reproduce

1. Download the [https://github.com/games647/LambdaAttack/releases/tag/2.4.0](https://github.com/games647/LambdaAttack/releases/tag/2.4.0) program

2. Start MSH

3. Send in 1 client with any version using the program

4. Server crash

### MSH Logs

```
╔═════════════════════════════════════════════╗
║  _ __ ___  ___| |__                         ║
║ | '_ ` _ \/ __| '_ \                        ║
║ | | | | | \__ \ | | | v2.4.7                ║
║ |_| |_| |_|___/_| |_| 3b9a95f               ║
║ Copyright (C) 2019-2022 gekigek99           ║
║ github: https://github.com/gekigek99        ║
║ remember to give a star to this repository! ║
╚═════════════════════════════════════════════╝
2022/07/31 09:02:49 [info  ≡   ] checking OS support...
2022/07/31 09:02:49 [info  ≡   ] loading config...
2022/07/31 09:02:49 [info  ≡   ] reading config file: "/root/mcsv/msh-config.jso                                                                                                                                 n"
2022/07/31 09:02:49 [error ≡   ] loadDefault: getVersionInfo: minecraft server v                                                                                                                                   ersion and protocol could not be extracted from version.json
2022/07/31 09:02:49 [info  ≡≡≡≡] setting log level to: 2
2022/07/31 09:02:49 [info  ≡≡≡ ] eula.txt exist and is set to true
2022/07/31 09:02:50 [info  ≡≡≡ ] minecraft server will now pre-warm (AllowSuspen                                                                                                                                   d is enabled)...
2022/07/31 09:02:50 [info  ≡≡≡ ] MINECRAFT SERVER IS STARTING!
2022/07/31 09:02:50 [info  ≡≡≡ ] listening for new clients to connect on 0.0.0.0                                                                                                                                   :41539 ...
2022/07/31 09:02:53 [serv  ≡≡  ] Starting net.fabricmc.loader.impl.game.minecraf                                                                                                                                   t.BundlerClassPathCapture
2022/07/31 09:02:57 [serv  ≡≡  ] [02:02:57] [main/INFO]: Loading Minecraft 1.18.                                                                                                                                   2 with Fabric Loader 0.14.8
2022/07/31 09:02:58 [serv  ≡≡  ] [02:02:58] [main/INFO]: Loading 3 mods:
2022/07/31 09:02:58 [serv  ≡≡  ]        - fabricloader 0.14.8
2022/07/31 09:02:58 [serv  ≡≡  ]        - java 17
2022/07/31 09:02:58 [serv  ≡≡  ]        - minecraft 1.18.2
2022/07/31 09:02:58 [serv  ≡≡  ] [02:02:58] [main/INFO]: SpongePowered MIXIN Sub                                                                                                                                   system Version=0.8.5 Source=file:/root/mcsv/libraries/net/fabricmc/sponge-mixin/                                                                                                                                   0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=S                                                                                                                                   ERVER
panic: runtime error: index out of range [1] with length 1

goroutine 115 [running]:
msh/lib/conn.getReqType(0x369380, 0x4000120318, 0x13, 0x1, 0xe, 0x6cfe4, 0x318fc                                                                                                                                   8, 0x400024a200, 0x4000218d08)
        C:/Users/Giacomo/Desktop/Documenti portatile/giacomo/Programmazione/» Go                                                                                                                                   /minecraft-server-hibernation/msh/lib/conn/conn-prot.go:141 +0x6e4
msh/lib/conn.HandleClientSocket(0x369380, 0x4000120318)
        C:/Users/Giacomo/Desktop/Documenti portatile/giacomo/Programmazione/» Go                                                                                                                                   /minecraft-server-hibernation/msh/lib/conn/conn.go:24 +0xd0
created by main.main
        C:/Users/Giacomo/Desktop/Documenti portatile/giacomo/Programmazione/» Go                                                                                                                                   /minecraft-server-hibernation/msh/minecraft-server-hibernation.go:73 +0x334
```

### MSH-Version

2.4.7 ARM64 (from github release page)

### Operating system

Debian 11

### Minecraft Version

Any version from the attack program

### Minecraft Server Software

Fabric 1.18.2 - no mods installed

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by SeasonPhan** [comment] 2022-07-31 02:31
`
╔═════════════════════════════════════════════╗
║  _ __ ___  ___| |__                         ║
║ | '_ ` _ \/ __| '_ \                        ║
║ | | | | | \__ \ | | | v2.4.7                ║
║ |_| |_| |_|___/_| |_| 3b9a95f               ║
║ Copyright (C) 2019-2022 gekigek99           ║
║ github: https://github.com/gekigek99        ║
║ remember to give a star to this repository! ║
╚═════════════════════════════════════════════╝
2022/07/31 09:27:01 [info  ≡   ] checking OS support...
2022/07/31 09:27:01 [info  ≡   ] loading config...
2022/07/31 09:27:01 [info  ≡   ] reading config file: "/root/mcsv/msh-config.json"
2022/07/31 09:27:01 [error ≡   ] loadDefault: getVersionInfo: minecraft server version and protocol could not be extracted from version.json
2022/07/31 09:27:01 [info  ≡≡≡≡] setting log level to: 4
2022/07/31 09:27:01 [info  ≡≡≡ ] eula.txt exist and is set to true
2022/07/31 09:27:02 [info  ≡   ] msh proxy setup: 0.0.0.0:41539 --> 127.0.0.1:25555
2022/07/31 09:27:02 [info  ≡   ] scaled /root/mcsv/server-icon-frozen.png to 64x64. (1 ms)
2022/07/31 09:27:02 [info  ≡   ] sendApi2Req: sending request
2022/07/31 09:27:02 [byte      ] msh --> mshc:{"prot-v":2,"msh":{"id":"2908f1cbae56d07988d84da13fae0a442d5675cd","msh-v":"v2.4.7","uptime":0,"allow-suspend":true,"sgm":{"seconds":0,"seconds-hibe":0,"cpu-usage":0,"mem-usage":0,"play-second-sum":0,"preterm":false}},"machine":{"os":"linux","arch":"arm64","java-v":"openjdk 17.0.4 2022-07-19","cpu-model":"ARMv8 Processor rev 0 (v8l)","cpu-vendor":"ARM","cores-msh":4,"cores-sys":4,"mem":4002668544},"server":{"uptime":0,"ms-v":"1.15.2","ms-prot":578}}
2022/07/31 09:27:03 [info  ≡   ] segment reset
2022/07/31 09:27:03 [info  ≡≡≡ ] minecraft server will now pre-warm (AllowSuspend is enabled)...
2022/07/31 09:27:03 [info  ≡   ] warming minecraft server...
2022/07/31 09:27:03 [info  ≡≡≡ ] MINECRAFT SERVER IS STARTING!
2022/07/31 09:27:03 [info  ≡   ] waitForExit: terminal started
2022/07/31 09:27:03 [info  ≡≡≡ ] listening for new clients to connect on 0.0.0.0:41539 ...
2022/07/31 09:27:03 [info  ≡   ] readApi2Res: reading response
2022/07/31 09:27:03 [byte      ] mshc --> msh:[123 34 82 101 115 117 108 116 34 58 34 117 110 111 34 44 34 100 101 118 34 58 123 34 118 101 114 115 105 111 110 34 58 34 118 50 46 52 46 54 34 44 34 100 97 116 101 34 58 34 50 48 50 50 45 48 52 45 48 50 34 44 34 99 111 109 109 105 116 34 58 34 51 98 54 54 102 49 54 49 102 54 50 48 100 54 49 101 52 56 49 52 97 99 97 57 57 49 57 97 100 100 98 50 54 55 97 57 56 98 48 100 34 125 44 34 111 102 102 105 99 105 97 108 34 58 123 34 118 101 114 115 105 111 110 34 58 34 118 50 46 52 46 48 34 44 34 100 97 116 101 34 58 34 50 48 50 49 45 48 52 45 50 54 34 44 34 99 111 109 109 105 116 34 58 34 98 48 102 48 98 57 102 100 50 102 50 52 98 48 48 51 97 97 55 50 100 55 57 56 101 50 54 102 55 56 101 101 48 52 53 98 52 55 52 100 34 125 44 34 100 101 112 114 101 99 97 116 101 100 34 58 123 34 118 101 114 115 105 111 110 34 58 34 118 50 46 48 46 48 34 44 34 100 97 116 101 34 58 34 50 48 50 48 45 49 49 45 49 54 34 44 34 99 111 109 109 105 116 34 58 34 49 55 102 55 56 56 101 54 56 100 101 98 99 99 48 51 56 98 50 53 50 57 52 48 100 52 54 52 54 51 55 97 53 101 49 48 56 57 49 99 34 125 44 34 77 101 115 115 97 103 101 115 34 58 91 93 125]
2022/07/31 09:27:05 [byte      ] client --> msh:[20 0 194 4 13 98 108 111 99 107 97 114 101 110 97 46 103 97 99 221 2]
panic: runtime error: index out of range [1] with length 1

goroutine 47 [running]:
msh/lib/conn.getReqType(0x369380, 0x40000961e8, 0x14, 0x1, 0xe, 0x6cfe4, 0x318fc8, 0x4000228c00, 0x40003a1d08)
        C:/Users/Giacomo/Desktop/Documenti portatile/giacomo/Programmazione/» Go/minecraft-server-hibernation/msh/lib/conn/conn-prot.go:141 +0x6e4
msh/lib/conn.HandleClientSocket(0x369380, 0x40000961e8)
        C:/Users/Giacomo/Desktop/Documenti portatile/giacomo/Programmazione/» Go/minecraft-server-hibernation/msh/lib/conn/conn.go:24 +0xd0
created by main.main
        C:/Users/Giacomo/Desktop/Documenti portatile/giacomo/Programmazione/» Go/minecraft-server-hibernation/msh/minecraft-server-hibernation.go:73 +0x334
`

this is a more detailed log with both attack client and msh's protocol version set to 1.15.2
note: it doesnt matter if the server is fully started or not, msh always crash with this type of connection

**Comment by gekigek99** [comment] 2022-11-16 17:57
should be fixed in 1b84d506d058bed7a603b49f36b92577c4fef7b8

compile the dev branch and tell me if you confirm, so I can close the issue.

_if you use msh and want to support it please give a star and consider becoming a sponsor_

**Closed** 2022-11-18 00:04 UTC
Labels: bug, closing

**Comment by gekigek99** [comment] 2022-11-18 00:07
thanks for reporting btw, I really appreciate it

**Comment by SeasonPhan** [comment] 2022-11-22 02:19
sorry for this late reply,
it has been awhile since i use MSH

i did try to reproduce the bug with 2.4.7 (setup was a 1:1 copy & on the same hardware+OS) but i cannot recreate it
i only got the message "Disconnected: multiplayer.disconnect.outdated_client" from the lambda program

i compiled dev branch (still, same setup) and i saw no errors at all
sadly i cannot confirm this from my side but i would like to know how you reproduced it

thanks you for fixing it 💙

**Comment by gekigek99** [comment] 2022-11-22 08:33
I hard codingly replaced these bytes in a normal request: `[ 20 0 194 4 13 98 108 111 99 107 97 114 101 110 97 46 103 97 99 221 2 ]`.

(I guess that if you want you can send that series of bytes to msh without even changing the code but i was lazy)

The problem was that msh after a series of bytes ending with `2`, it expected an other packet... Which the botting tool was not providing and this lead to a wrong array access.

It's a behaviour that should not happen on a normal client connection, but still worth fixing as not msh is more robust to rogue/wrong packets.

**Comment by gekigek99** [comment] 2022-11-22 09:55
Well, that erroneus packet might have been caused by network or by a botting tool bug.

Either way it was a nice catch as in production you cannot know what clients will be sending to the server.
